### ISSUE TITLE
Operator precedence is not working

### ISSUE THREAD

**Issue by koniq** [jaystack/odata-v4-parser#4]
According to [odata V4 documentation](http://docs.oasis-open.org/odata/odata/v4.0/csprd01/part2-url-conventions/odata-v4.0-csprd01-part2-url-conventions.html#_Toc355091904) operator order precedence should be : NOT, AND, OR. 

Considering search example '$search=black OR red AND blue OR white' : parsed json object should have (according to odata V4 docs) structure equal to object for request '$search=black OR (red AND blue) OR white' but object received from 'query' function suggests that it is equal to '$search=black OR (red AND (blue OR white))'. Current and expected json files representing objects are added to this issue (simplified - without 'position' and 'next' values). 

[expectedSimplifiedResult.txt](https://github.com/jaystack/odata-v4-parser/files/651959/expectedSimplifiedResult.txt)
[currentSimplifiedResult.txt](https://github.com/jaystack/odata-v4-parser/files/651958/currentSimplifiedResult.txt)

Is it possible that you can prepare a fix in a short time ?

Best, 

Koniq

**Comment by forivall** [comment]
This looks like it's been fixed and can be closed?

https://gist.github.com/forivall/39f0a6089478ef3cdfcf29488ecd02ce

**Comment by lazarv** [comment]
Yes, this was solved, I close this now.
