### ISSUE TITLE
Expand issue

### ISSUE THREAD

**Issue by bastienlemaitre** [jaystack/odata-v4-parser#9]
Hi, when i run this following code :
```js
var parsed = parser.query(
  `$expand=group,user`
);
var queryOptions = parsed.value.options;
var expand = queryOptions.filter(q => q.type == 'Expand');
```
It miss "user" token, and "group" token is found twice..

![image](https://user-images.githubusercontent.com/11610748/34575161-03b525cc-f17a-11e7-9861-f1eca4f419d1.png)

Thanks

**Comment by lazarv** [comment]
Thank you @bastienlemaitre for finding this bug. A fixed version is now available on npm. Please run ```npm update```.
